version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: main
    labels:
      - dependencies

  - package-ecosystem: 'docker'
    directory: '/cli'
    schedule:
      interval: 'daily'
    target-branch: main
    labels:
      - dependencies
